### ISSUE TITLE
crome explore : 요청하신 URL을 서버에서 찾을 수 없습니다. 라고 나와요

### ISSUE THREAD

**Issue by sbs950** [changdoc/naver-vaccine-macro#1]
코드 다운 받아서 실행 할 수 있게 해주세요.

**Comment by changdoc** [comment]
아직 구글 크롬 스토어에서 심사중인 상태네요.
공개 되면 다시 코멘트 남기도록 하겠습니다.

**Comment by changdoc** [comment]
https://chrome.google.com/webstore/detail/naver-vaccine-macro/alfhbmpnlhcpcjjaacapcdnggegicepl?hl=ko&authuser=0

에 공개 되었습니다
