### ISSUE TITLE
백신이 있어도 페이지 새고고침 되는 현상

### ISSUE THREAD

**Issue by OneTop4458** [changdoc/naver-vaccine-macro#10]
안녕하세요
1.0.1 버전 매크로를 사용하였는데

백신이 발견되었는데 페이지가 새고고침 되며
예약 시도도 안 하고 계속 새고고침만 하네요 ㅠㅠ

텔레그램 연동도 해놨는데 아무런 메시지도 안 왔습니다

**Comment by changdoc** [comment]
아... 혹시 잔여 백신 종류가
아스트라제네카, 얀센, 화이자 말고 다른 종류였을까요?

**Comment by OneTop4458** [comment]
아뇨 화이자 백신이였습니다
눈으로 잔여수량 2개 남은게 보였는데

그냥 예약 시도 없이 계속 새고고침 되었네요

**Comment by OneTop4458** [comment]
일단 마스터로 교체 후 월요일날 다시 시도해보겠습니다.

**Comment by changdoc** [comment]
오늘 테스트 해본 결과 저는 정상적으로 디텍팅을 하긴 했어서 페이지에 변화가 있었는지 확인이 안되네요.
master로 사용하시는게 좋겠습니다.

**Comment by changdocjjang** [comment]
마스터로 교체한다는게
크롬 앱이 아니라 이 사이트에서 프로그램 받아서
크롬 관리자 모드로 설치하란 말씀이신가요

**Comment by OneTop4458** [comment]
1. 기존 확장 프로그램 제거
2. https://github.com/changdoc/naver-vaccine-macro
3. code -> download zip 클릭
4. 압축 해지
5. 크롬 확장 프로그램 설정 메뉴 이동
6. 개발자 모드 켜기
7. 압축 해제된 확장 프로그램 로드에 압축 풀린 폴더 선택

**Comment by changdocjjang** [comment]
아 넵 감사합니다

**Comment by OneTop4458** [comment]
@changdoc 흠 방금도 마스터로 교체 후
실행 중 잔여 백신이 떴었는데 예약 자체를 안누르네요 ㅠ

버그 인듯 합니다.

**Comment by changdocjjang** [comment]
아 어쩐지 저도 교체하니까 어제는 오류창이라도 떴었는데
오늘은 그것조차 없이 계속 새로고침만 되네요

**Comment by OneTop4458** [comment]
혹시 개인정보 이슈(https://github.com/changdoc/naver-vaccine-macro/issues/9)
때문인건 아닐까요?

저도 개인정보 동의창이 존재하긴 합니다.

**Comment by changdocjjang** [comment]
네 어제는 그 창이 있는 상태에서
계속 진행하더라도 오류창까지는 갔는데
오늘 교체 한 프로그램은 하루종일 오류창조차 안뜨네요
원탑님 말씀대로 백신 에약이 제대로 안이뤄지는거같아요

**Comment by changdoc** [comment]
음.. 넵 
오류창이 뜨고 나면 새로고침이 멈춰버리는 이슈가 있어서 대응한 부분이 있는데 그부분이 영향인지 확인해보겠습니다.

**Comment by changdoc** [comment]
우선 에러  디텍팅 하는 부분 처리 추가한 부분 동작하지 않도록 수정한 부분 푸시해뒀습니다.

master로 확인해주세요~

**Comment by hyunie88** [comment]
저번 성공 이후 지인 백신도 성공했었는데 언급되었던 동의부분은 신청과 관련이 없었던 것같아요. 어제 오후에 동의 관련 수정 전 버전으로 해서 동의 체크되어있지 않으나 시도해서 정상 진행완료. (저번과 동일하게 오류페이지가 나오나 병원에서 연락옴)

어제 저녁 크롬에도 업데이트 된 걸 보고 지인 2명에게 확장 프로그램 주소만 줬구요
그 지인 2명도 오늘 모두 성공하여  백신 접종하였습니다.

도움이되실까 하여 남기고갑니다.

**Comment by changdocjjang** [comment]
88님 정보 감사합니다

**Comment by OneTop4458** [comment]
그럼 내일 pc 2대를 사용하여

마스터 , 크롬 확장 프로그램 두가지 버전으로 시도해 보겠습니다

참고로 오늘은 모두 아침자로 마스터 받아서 2명정도 같이 저랑 시도 해봤는데 모두 새고고침 만 되었습니다.

**Comment by changdocjjang** [comment]
> 저번 성공 이후 지인 백신도 성공했었는데 언급되었던 동의부분은 신청과 관련이 없었던 것같아요. 어제 오후에 동의 관련 수정 전 버전으로 해서 동의 체크되어있지 않으나 시도해서 정상 진행완료. (저번과 동일하게 오류페이지가 나오나 병원에서 연락옴)
> 
> 어제 저녁 크롬에도 업데이트 된 걸 보고 지인 2명에게 확장 프로그램 주소만 줬구요
> 그 지인 2명도 오늘 모두 성공하여 백신 접종하였습니다.
> 
> 도움이되실까 하여 남기고갑니다.

혹시 88님은 신청 화면 하단에 동의란 없었나요

**Comment by hyunie88** [comment]
네 어제 동의 관련 이슈로 변경되기 전 버전 사용일 때, 예약 시도를 한 번도 안했던 지인이라 동의 체크가 안되어있었어요.

**Comment by OneTop4458** [comment]
혹시 인터벌 같은 건 따로 조절하셨는지랑
백신 타입 아무거나, 화이자 중 어떤 걸로 하셨는지

텔레 연동 여부 이렇게 3가지 여쭈어봐도 될까요?

**Comment by hyunie88** [comment]
아무거나/인터벌 그대로 1000/텔레그램 연동X 였습니다.

**Comment by hyunie88** [comment]
엇 저도 오늘 스킵 현상을 확인했습니다. 동의는 이미 완료된 아이디인데 백신 예약신청이 초록색으로 활성화 되어있고 화이장 수량이 2임에도 다음단계로 진행이 안되고 계속 새고가 되고 있었네요.

**Comment by OneTop4458** [comment]
@hyunie88  마스터로 진행하신 건가요?

**Comment by changdoc** [comment]
음... 신청 가능 상태를 판단하는 부분이 동작 안하고 있는 상황일거 같기도 하네요.
페이지 레이아웃이 바뀌었다면 신청 가능한 상태 판단 자체를 못 하고 있을 가능성이 있는데요. 확인해보도록 하겠습니다

**Comment by changdoc** [comment]
처음 만들때 스크린샷이긴한데요.
![image](https://user-images.githubusercontent.com/1879494/125148077-a7a01000-e16a-11eb-9930-36040db0c2f6.png)
잔여 백신 수량 체크가 잘 되고 있는지 확인하려고 예약 신청할 백신 이름과 수량의 글자 배경 색깔을 변경하는 코드가 들어가 있는데요.
수량이 0 이상이면 녹색 배경으로 보이게 되는데
@hyunie88 혹시 잔여 수량이 있을때 화면에 
화이자 2  이 부분이 배경 녹색으로 잘 표시 되었는지 기억 나실까요?

**Comment by OneTop4458** [comment]
1초 주기로 새고고침 되어서 자세히는 본 것이 아니지만
제 기억상 저런 체크박스가 없었고 그냥 화이자 잔여 2만 뜨고 예약 신청 버튼만 활성화 되어있었던 것 같습니다.

주석에 아래와 같은 메시지가 생긴 것으로 보아 현재 화이자 밖에 안뜨니 백신 선택란은 지운 것이 아닐까 생각이 되네요

**Comment by changdocjjang** [comment]
그제는 오류페이지 3번은 봤는데
어제 오늘은 오류페이지 조차 안나와요
아마 에약 제대로 안되는거같아요
색 말고 숫자 0이 아니면 예약 시도하는방법은 어떨까요 제작자님

**Comment by changdocjjang** [comment]
아 물론 오류페이지 어제부터 안뜨는데
어제는 마스터로 오늘은 크롬앱에서 다운받아서 시도중입니다

**Comment by changdoc** [comment]
색상으로 판단하는건 아니고요 0이 아닐때 시도하게 만들어져있는상태입니다.
색상은 동작이 정상적인지 확인 하려고 넣어둔거라서요.

색상 변화가 있었다면 잔여 수량 파악은 문제 없음 으로 보시면 되는 거죠

**Comment by hyunie88** [comment]
정확한 기억은 아니지만 백신이나 수량 부분에 색상 변화가 없었던 것 같습니다.

**Comment by massu850310** [comment]
![test](https://user-images.githubusercontent.com/46388422/125148801-bb9a4080-e16f-11eb-93c5-8eeedecb3046.png)

화이자에 잔여 1
테스트모드 돌렸구
타다! 소리까지 들었습니다

**Comment by OneTop4458** [comment]
흠 그럼 둘 중 하나의 경우 밖에 없을 듯 하네요.

1. 예약 신청 버튼의 코드 변경
2. 타이밍 문제로 인한 실패 (리프래쉬 딜레이 변경 시 해소 가능 기대)

**Comment by changdocjjang** [comment]
ㅠㅠㅠ

**Comment by changdoc** [comment]
@massu850310 감사합니다.

예약을 시도하는 방식을 현재 url 변경으로 처리 중인데 신청 버튼을 클릭하는 형태로 변경해보도록 하겠습니다.

**Comment by changdoc** [comment]
https://github.com/changdoc/naver-vaccine-macro/commit/18bff62310038602e88c20b420541a523e7d954e

예약 시도 하는 방식을 예약 신청 버튼 click event 발생시키는 형태로 변경했습니다.

저도 계속 테스트로 확인 중이긴한데... 시도 해보도록 하겠습니다.

**Comment by changdoc** [comment]
조금 전에 잔여 백신이 발생해서
변경한 click event 발생시키는 방식으로 백신 예약 신청 시도까지 정상적으로 되는 부분 확인 했습니다만.. 

어제 신청 시도를 한번 해서 정보 제공 동의가 표시되고 있는 상황은 아니였어서;; 정상적으로 수정했는지 확인 할 수가 없네요.

**Comment by changdoc** [comment]
정보 제공 동의 표시 되는 상황까지 확인 진행중입니다.

정상적으로 동작할 것으로 기대가 되긴한데.. 크롬 쪽은 어제 등록한게 아직 승인이 안나서 추가 패치를 못하는 상황이네요

**Comment by OneTop4458** [comment]
우선 오늘도 돌려본 결과
크롬 스토어에 있는 버전 및 오늘 아침 9시 마스터 기준

잔여백신 발생 알림이 여러 차래 발생 했지만 모두 예약 되지 않았네요

내일 다시 내일 아침 기준 마스터 받아서 돌려보겠습니다.

**Comment by massu850310** [comment]
@OneTop4458 전 지인 PC에 해줬는데 성공해서 12시에 맞으러 갔어요...

설정은 백신종류: 화이자
외에는 건들지 않았습니다

버전은 1.0.2 master 아침 8시꺼로 했어요

**Comment by OneTop4458** [comment]
흠 그럼 계정이 문제일까요 ㅠㅠ

저는 지금 구버전 부터 최신까지 한 4일 넘게 계속 돌려도
계속 새고고침 반복 + 잔여 백신 알람은 뜸 이 경우만 나오네요..

사용 장비도 회사랑 집 지인 pc 등등 총 4대가 넘는 장비로 시도해봐도 다 실패 하네요..
저와 동일 케이스가 발생하시는 분들도 몇 분 계시니 제 환경 문제만은 아닌 것 같은데..

**Comment by massu850310** [comment]
@OneTop4458 흠... 현상 재현이 되야 개발자님도 봐주실텐데 ㅠㅠ

아, 정보제공 동의란은 보이고 있었어요 지인 계정은

**Comment by changdoc** [comment]
크롬 측이 이전 버전(1.0.2) 승인 나는대로 1.0.3으로 배포 진행해두도록 하겠습니다.
내일은 일요일이라 잔여 백신 뜨는 병원이 없을듯 해서 월요일에 최신 버전(1.0.3)에서 확인 해보시는게 좋을 듯합니다.

**Comment by changdoc** [comment]
@OneTop4458 1.0.3 버전으로 진행시에도 잔여 백신이 떴는데 예약 신청 시도를 안한다면 
![image](https://user-images.githubusercontent.com/1879494/125157207-81976180-e1a4-11eb-9239-12f8c099db67.png)
esc를 눌러 자동 새로고침 안되도록 하셔서 개발자 도구에서 console 창 캡쳐해서 공유해주시면 원인 파악에 도움이 될 것 같습니다.

뭔가 동작을 안하고 새로고침이 되고 있다면 console창에 필요로 하는 정보가 있을 것 같아요.

**Comment by hyunie88** [comment]
1.0.3 버전으로 금일 성공했습니다.
다만 사운드 발생이나 텔레그램으로 메세지 전송이 안되었어요.
텔레그램은 처음 연동 시도 메세지는 정상적으로 확인했엇습니다.
![WWW](https://user-images.githubusercontent.com/70103279/125179909-7a1c9a80-e22e-11eb-97a3-5c9694efa5ad.JPG)

**Comment by changdocjjang** [comment]
> 1.0.3 버전으로 금일 성공했습니다.
> 다만 사운드 발생이나 텔레그램으로 메세지 전송이 안되었어요.
> 텔레그램은 처음 연동 시도 메세지는 정상적으로 확인했엇습니다.
> ![WWW](https://user-images.githubusercontent.com/70103279/125179909-7a1c9a80-e22e-11eb-97a3-5c9694efa5ad.JPG)
크롬앱으로 하신건가요

**Comment by changdocjjang** [comment]
오늘 오류창만 5번 뜨고 예약이 안되네요 ㅠㅠㅠ

**Comment by OneTop4458** [comment]
어떤 오류가 뜨시나요?
오늘은 일요일이라 백신 접종 하는곳이 매우 드물어서 그런 거 일 확률이 높습니다.

네이버는 영업 안하는 병원도 대기중으로 뿌려주더라구요 카카오에서 해당 병원이 금일 영업 하는지 확인 해 보세요

**Comment by changdocjjang** [comment]
![image](https://user-images.githubusercontent.com/87104616/125181619-9d9d1080-e241-11eb-9f10-9ee594e720b7.png)
이런 오류가 뜹니다 오늘만 5번쨰네요

**Comment by changdoc** [comment]
저 에러 페이지는 네이버 페이지 로드 중에 발생하는 에러긴한데요 에러 페이지 노출시 새로고친 하던 부분을 제거 해뒀는데 다시 동작하도록 바꾸는게 좋겠네요

**Comment by changdoc** [comment]
에러 페이지 검출시 동작이 멈추지 않도록 새로 고침 자동으로 하는 기능 복구 해서 1.0.4로 생성해두었습니다.
https://github.com/changdoc/naver-vaccine-macro/releases/tag/v1.0.4

**Comment by changdoc** [comment]
![image](https://user-images.githubusercontent.com/1879494/125183488-dc3ac700-e251-11eb-8de6-42fe4fd1848d.png)
저도 조금 전에 재현됐습니다;

에러 페이지 레이아웃이 바뀌어서 아예 시도를 못하고 있는 상황이 있는거군요.
다시 수정하겠습니다.

**Comment by changdoc** [comment]
https://github.com/changdoc/naver-vaccine-macro/releases/tag/v1.0.4.1
1.0.4.1 버전으로 생성해두었습니다.

**Comment by OneTop4458** [comment]
오늘 1.0.3 버전으로 시도해 보았으나 실패했네요 ㅋㅋ..

잔여 수량 5가 떴고 발생 하자마자 매크로는 여전히 계속 새고고침을 하길래 그냥 수동으로 예약 신청 눌렀는데
실패 떴네요 ㅠ [수동으로 눌러서 실패나니 텔레로 실패 알림은 왔습니다]

내일 또 시도를 해보겠습니다

**Comment by changdoc** [comment]
수량이 뜨면 에러 페이지가 따로 나오지 않고 예약 시도를 하게 만들어져 있는데요. 음.. 왜 시도를 안하게 되는지 예상이 안됩니다.

매크로 동작 중인 상태에서 클릭으 별도로 막거나 하진 않아서 지속적으로 예약 시도 안되고 있다면 
제가 파악 불가능한 원인으로 동작을 안하는듯 하니 
잔여 수량 떴을때 수동으로 신청 버튼을 누르시는게 나을것 같습니다.

개인 정보 동의가 안뜨는건 
예약 시도를 한번 하고 나면 성공/실패 상관없이 개인정보 제공 동의가 되어있는 상태로 바뀌게 되어 그런거 같더라고요. (예약 시도 처리 과정에 정보 제공 동의를 저장하는것으로 예상됩니다.)

**Comment by changdocjjang** [comment]
> 수량이 뜨면 에러 페이지가 따로 나오지 않고 예약 시도를 하게 만들어져 있는데요. 음.. 왜 시도를 안하게 되는지 예상이 안됩니다.
> 
> 매크로 동작 중인 상태에서 클릭으 별도로 막거나 하진 않아서 지속적으로 예약 시도 안되고 있다면
> 제가 파악 불가능한 원인으로 동작을 안하는듯 하니
> 잔여 수량 떴을때 수동으로 신청 버튼을 누르시는게 나을것 같습니다.
> 
> 개인 정보 동의가 안뜨는건
> 예약 시도를 한번 하고 나면 성공/실패 상관없이 개인정보 제공 동의가 되어있는 상태로 바뀌게 되어 그런거 같더라고요. (예약 시도 처리 과정에 정보 제공 동의를 저장하는것으로 예상됩니다.)

예 맞습니다 신청전엔 무조건 개인정보동의창이 하단에 노출되고
한번 실패 후 없어집니다

**Comment by hyunie88** [comment]
여태까지 성공은 모두 크롬으로 했습니다.
빠른 피드백 해주신 덕분에 저뿐만아니라 지인들까지 도움주고있어요,
정말 감사드립니다!

**Comment by changdocjjang** [comment]
> 여태까지 성공은 모두 크롬으로 했습니다.
> 빠른 피드백 해주신 덕분에 저뿐만아니라 지인들까지 도움주고있어요,
> 정말 감사드립니다!

하 저도 빨리 성공하고 남들 도움 주고싶은데 오류페이지만 뜨네요
크롬앱에 화이자만 선택하시는거죠?

**Comment by OneTop4458** [comment]
> > 여태까지 성공은 모두 크롬으로 했습니다.
> > 빠른 피드백 해주신 덕분에 저뿐만아니라 지인들까지 도움주고있어요,
> > 정말 감사드립니다!
> 
> 하 저도 빨리 성공하고 남들 도움 주고싶은데 오류페이지만 뜨네요
> 크롬앱에 화이자만 선택하시는거죠?

아무거나로 선택해도 된다고 합니다.
내일부터는 모더나도 풀릴 예정이니

아무거나로 두시는게 좋을 듯 합니다.

**Comment by OneTop4458** [comment]
그리고 이건 추측인데 모둔 새고고침만 당한 시스템에는
네이버 웨일 (크로미움)이 깔려있긴한데 이게 원인은 아니겠죠?..

**Comment by changdoc** [comment]
네이버 웨일 브라우저에서는 제가 테스트를 해본 적이 없긴한데.. 동작이 다르지는 않아서 문제가 될지는 모르겠네요. (내일 웨일로도 테스트 돌려 봐야겠네요)

오히려 다른 확장 프로그램과의 충돌이 있다면 예약 시도가 안될수도 있을거 같긴하군요.

**Comment by OneTop4458** [comment]
아 매크로 작동은 크롬에서 했는데
os에 웨일이 깔려 있고 
크롬으로 매크로 돌려두고 웨일로는 그냥 인터넷 사용하는 경우였습니다.

크롬 스토리지? 인가 쓰신다 해서 혹시 크로미움 브라우저들과 뭔가 충돌이 있나 해서요
아님 말씀하신 것 처럼 웨일에 깔린 확장 프로그램이 문제일 수도 있겠네요

**Comment by massu850310** [comment]
아까 오전 11시 기준 1.0.4 성공했습니다

**Comment by hyunie88** [comment]
오후 1시6분, 화이자 성공, 알람음, 텔레알람 정상 작동이요.

**Comment by OneTop4458** [comment]
네이버 웨일 지우고 시도하니 정상 작동 됩니다.

화이자 성공, 알람음, 텔레알람 정상

**Comment by changdocjjang** [comment]
성공했습니다 감사합니다

**Comment by OneTop4458** [comment]
추가적으로 예약 성공률은 18bff62310038602e88c20b420541a523e7d954e 이전이 더 높은 듯 합니다.
버튼 클릭은 질병 서버 응답 오류가 너무 잦더군요..

**Comment by changdoc** [comment]
질병 서버 응답 오류는 클릭 처리와 무관할것으로 예상되어 현재로 유지하려고합니다.

크롬 스토어 측에 1.0.4 공개될때 본 이슈도 close하겠습니다. 스레드가 너무 길어서 페이지 여는데도 오래걸리네요.

**Comment by OneTop4458** [comment]
@changdoc 
감사합니다.
감사의 의미로 커피 기프티콘이라도 보내드리고 싶은데
연락 방법이 있을까요?.

**Comment by changdoc** [comment]
엇 괜찮습니다~
여러 오류 상황들을 제보해주셔서 예외처리들이 잘 추가되어서 많은 도움이 됐습니다. 감사합니다.

**Comment by changdocjjang** [comment]
저도 기프티콘 보내드리고 싶은데 
카카오오픈채팅방이라도 파주세요
그리고 코딩 관심 생겼는데 많이 배우고싶습니다

**Comment by changdoc** [comment]
괜찮습니다 ^^;

@changdocjjang 
제가 작업한 부분은 간단한 부분이라 관심이 생겼다면 HTML, CSS, JAVASCRIPT 이렇게 3가지 관련된 입문 서적 하나 구하셔서 기초 부터 공부하시면 될 것 같네요~

**Comment by changdoc** [comment]
크롬 웹스토어에 1.0.4 버전 (github 기준 1.0.4.1) 이 공개되어 본 건 close하도록 하겠습니다.

**Comment by changdocjjang** [comment]
> 괜찮습니다 ^^;
> 
> @changdocjjang
> 제가 작업한 부분은 간단한 부분이라 관심이 생겼다면 HTML, CSS, JAVASCRIPT 이렇게 3가지 관련된 입문 서적 하나 구하셔서 기초 부터 공부하시면 될 것 같네요~

그래도 스벅 깊콘 하나라도 보내드리고 싶네요 제작자님 방법 없을까요?
일단 파이썬부터 파보려고 했는데 제가 잘못 짚는건가요?
파이썬 노트북 이쪽으로 블로그 눈팅중인데 말씀하신 3가지 부터 공부해야 맞는건가요 제작자님?

**Comment by changdoc** [comment]
@changdocjjang 
네 마음만 받겠습니다~

제가 말한 3가지가 필수는 아니고요. 제가 작업한 이 프로젝트에서 사용된건 3가지라 말씀드려봤습니다.

파이썬도 괜찮은 입문용 언어로 알고 있습니다. 
뭐든 꾸준히 공부하시다 보면 자연스럽게 필요해지는것들을 찾게 되실것 같네요.

**Comment by changdocjjang** [comment]
> @changdocjjang
> 네 마음만 받겠습니다~
> 
> 제가 말한 3가지가 필수는 아니고요. 제가 작업한 이 프로젝트에서 사용된건 3가지라 말씀드려봤습니다.
> 
> 파이썬도 괜찮은 입문용 언어로 알고 있습니다.
> 뭐든 꾸준히 공부하시다 보면 자연스럽게 필요해지는것들을 찾게 되실것 같네요.

아 넵 꼭 드리고 싶은데 아쉽네요 제작자님
넵 일단 세가지 입문서적부터 보겠습니다
