### ISSUE TITLE
병원 orgCd 추출 부분 렉

### ISSUE THREAD

**Issue by massu850310** [changdoc/naver-vaccine-macro#13]
안녕하세요 개발자님
병원 orgCd 추출 부분이 input type="text"로 되어있어서 데이터 넣고 읽을때 많이 느리더라구요
textarea로 변경 시 이런 렉이 아예 없어지네요... 변경 검토 부탁드려요

`<input type="text" id="graphql_result">`
를
`<textarea id="graphql_result" style="width:270px;height:300px;"></textarea>`

**Comment by massu850310** [comment]
아

병원목록 추출 한번 진행하고 나면
popup.js
123번줄

오류나서 매크로 변경사항이 저장이 안되더라구요

textarea > input 으로 (원래대로) 해봐도 동일한 오류 발생합니다

**Comment by changdoc** [comment]
https://github.com/changdoc/naver-vaccine-macro/commit/1f08639356c4a66cad10e8ff6bb455edf0d61bc0

데이터 입력 영역 textarea로 변경했습니다.
데이터에 orgCd에 접근할 수 없는 데이터가 있을때 스크림트 오류가 나고 있었네요. 수정해두었습니다.

**Comment by massu850310** [comment]
잘 되네요 감사합니다 :)
