### ISSUE TITLE
잔여백신 매크로 사용 시 처벌

### ISSUE THREAD

**Issue by changdocjjang** [changdoc/naver-vaccine-macro#14]
![image](https://user-images.githubusercontent.com/87104616/125257593-8ab93780-e338-11eb-9461-81a9d701c730.png)
우선 제작자님 프로그램으로 예약 완료해서 너무 감사하게 생각합니다
관련 기사를 찾다가 업무 방해죄가 될 수 있다는 걸 확인했는데
제작자님과 다른 이용자분 의견은 어떠신지 궁금합니다

**Comment by changdoc** [comment]
법적으로 문제가 된다면 사용 못하게 되어야 하긴 할 거 같네요.

**Comment by syKim12** [comment]
안녕하세요 오늘 새벽에 너무 감사한 프로그램을 발견하게 돼서 남깁니다. 
교환학생으로 9월 출국을 앞두고 있어 꼭 예약을 해야하는데 혹시 사용 못하게 막을지 고민중이시라면 하루 이틀만 더 열어주실 수 있으실까요??

**Comment by changdocjjang** [comment]
![image](https://user-images.githubusercontent.com/87104616/125535204-fec2c5db-3b00-445e-86ec-a445bf943622.png)
일단 처벌은 가능한 상황이네요

**Comment by changdoc** [comment]
> 안녕하세요 오늘 새벽에 너무 감사한 프로그램을 발견하게 돼서 남깁니다.
> 교환학생으로 9월 출국을 앞두고 있어 꼭 예약을 해야하는데 혹시 사용 못하게 막을지 고민중이시라면 하루 이틀만 더 열어주실 수 있으실까요??
> 간절한 마음에 실례를 무릅쓰고 남깁니다ㅠㅠ

@syKim12 저는 당장 프로젝트를 닫거나 크롬 스토어에서 내릴 계획은 없습니다.
다만, 법적으로 문제가 생긴다면 네이버측에서 막는 상황이 먼저 발생할 것 같네요.

**Comment by syKim12** [comment]
프로그램 정말 감사드립니다!!!! 덕분에 예약 성공하고 방금 접종할 수 있었어요 감사합니다:)

**Comment by OneTop4458** [comment]
우선 정부의 입장은 아직까진 아래 사유로 굳이 관련 규정을 만들 이유가 없다 입니다.
참고 바랍니다.

1. 어차피 잔여 백신은 개인당 한번만 가능하다.
 > 매크로를 돌린 다 해도 어차피 개인당 한번 입니다.
    정부도 차피 1인당 한번 접종만 가능해서 관련 규제의 필요성을 아직 못 느낀다 라고 했구요
2. PC 예약자 수는 극히 드물다
 > 통계상 80% 이상 모바일 예약이며 PC 사용자 일부만 매크로 사용 문제가 존재 하지만 극히 일부이기 때문에 문제 없다 라는 입 
    장입니다.

**Comment by changdocjjang** [comment]
![image](https://user-images.githubusercontent.com/87104616/125730110-d925d874-e5d3-492c-8006-6d5afe07e546.png)

**Comment by changdoc** [comment]
기사 날짜가 5일인거 보면 좀 지난 뉴스긴하네요.
