### ISSUE TITLE
오류가 나도 신청들어가지더라구요

### ISSUE THREAD

**Issue by JINHYUKJEONG** [changdoc/naver-vaccine-macro#15]
신청돌아갈때 오류가떠도 신청들어간경우가있네요 오류날때도 오류창 떴다고 텔레그램알림올수있도록 수정부탁드려요 ㅠ

**Comment by changdoc** [comment]
신청 시도 후에 오류가 발생했을때 말씀이신거죠..?

최신 코드에서는 시도 했지만 오류 (제가 확인했던 오류 페이지 내용에는 질병관리청 응답 지연.. 등의 문구가 들어있었습니다.) 
페이지로 판단될 경우 -> 제가 확인 했을때는 브라우저 url에 error가 포함되어 있었습니다.
텔레그램으로 
'예약 시도 성공했습니다. 결과를 장담할 수 없습니다. (예를 들어, 질병 관리청 응답 지연). 에러 페이지 내용을 확인해주세요.'
메시지 전송하도록 해두었는데요.

시도하신 버전이 혹시 1.0.4버전이 아닐까요? 1.0.4 버전 이후 버전인데도 오류 났을때 메시지가 안왔다면
오류가 났을때 url 포함된 화면 캡쳐 공유해주시면 감사하겠습니다.

**Comment by changdoc** [comment]
혹시 스토어 버전을 계속 이용중이시라면 조금전에 1.0.4버전이 배포되었습니다. 최신 버전으로 갱신 후 확인 부탁드리겠습니다.

**Comment by JINHYUKJEONG** [comment]
일단알겠습니당.. 1.0.3 버전이용중이였거든요

**Comment by changdoc** [comment]
이슈는 close 해두겠습니다. 증상이 재현되는 경우 화면 캡쳐와 함께 reopen해주시면 감사하겠습니다.

**Comment by JINHYUKJEONG** [comment]
일단 불편해도 1.0.3 쓰렵니다 방금 화이자 5개떴는데도 가만히있더라구요 뜬상태에서
