### ISSUE TITLE
새로고침 주기 출력 오류

### ISSUE THREAD

**Issue by massu850310** [changdoc/naver-vaccine-macro#16]
새로고침 주기를 설정하면

Log 창에는 정상적으로 나옵니다
curr interval: 설정된값

근데 다시 옵션 눌러보면, 영 다른 숫자가 출력 되고 있습니다
500 설정 -> 1020 출력
600 설정 -> 1016 출력
![interval](https://user-images.githubusercontent.com/46388422/125579361-1ac2f933-bc6c-4f3e-a471-92f76e7a76c5.png)

**Comment by changdoc** [comment]
수정 하도록 하겠습니다. 구현하면서 빨라지는것만 확인하고 정상 출력 안되는 부분은 파악을 못하고 있었네요.

**Comment by changdoc** [comment]
https://github.com/changdoc/naver-vaccine-macro/commit/b581cccff1a634dd0cf6f5b5e9c17630e0ff5e2b

수정 해두었습니다.
