### ISSUE TITLE
5번째 실패입니다 제작자님

### ISSUE THREAD

**Issue by changdocjjang** [changdoc/naver-vaccine-macro#17]
어제 오늘 계속 이럽니다 ㅜㅜ

**Comment by JINHYUKJEONG** [comment]
쩝.. 저도 10번째도전했는데 실패중입니다

**Comment by changdoc** [comment]
네 예약 시스템 특성상 매크로가 무조건 최우선 예약 신청이 된다는 보장은 없습니다.

오류 메시지에도 적혀 있듯이 예약 처리가 
최종적으로는 질병 관리청 서버에서 이루어지는 것으로 보입니다.

동시에 예약 신청을 하게 되는 인원이 많은 거라 제가 어떻게 할 수 있는 부분이 없는 듯 하네요.


혹시 여러 탭을 많이 띄워두고 시도 중이시라면 동시에 시도하는 수를 좀 줄이셔야할 것 같습니다.

아무래도 페이지가 그려지고 나와있는 정보중에 잔여 백신이 있다고 판단한 뒤에 신청 시도를 하는거라 페이지 렌더링 시간이 조금이라도 딜레이가 된다면 예약 신청도 그만큼 느리게 진행됩니다.

**Comment by OneTop4458** [comment]
병원을 변경해 보세요.
경쟁자가 많이 몰리는 병원의 경우 매크로 써도 예약이 힘들더라구요..

그리고 저기선 실패 떠도 문자로 국민비서씨가 예약 성공이라고 오면 성공 된 겁니다.

**Comment by flaehdan** [comment]
혹시 성공하신 분들은 탭 몇개 열어두셨나요?

**Comment by OneTop4458** [comment]
보통 5개 정도 열어둡니다.
지인 포함 5명 정도 성공 시켜줬네요.

저게 위치 캐바캐가 솔직히 심하더라구요..
가산쪽은 @flaehdan 님 처럼 예약 실패가 거의 대부분 입니다.

실패 떠도 문자 꼭 확인하시고 새고고침 주기를 500ms로 줄여보는것도 방법이긴 합니다.

**Comment by changdocjjang** [comment]
> 보통 5개 정도 열어둡니다.
> 지인 포함 5명 정도 성공 시켜줬네요.
> 
> 저게 위치 캐바캐가 솔직히 심하더라구요..
> 가산쪽은 @flaehdan 님 처럼 예약 실패가 거의 대부분 입니다.
> 
> 실패 떠도 문자 꼭 확인하시고 새고고침 주기를 500ms로 줄여보는것도 방법이긴 합니다.

탭 5개에 새로고침 주기 500ms 참고하겠습니다 감사합니다
3일째 실패입니다 저는 오류만 10개 이상봤어요

**Comment by changdocjjang** [comment]
![image](https://user-images.githubusercontent.com/87104616/125730075-57bfc5f8-54af-4562-935c-ba51af7b0f08.png)

**Comment by JINHYUKJEONG** [comment]
@changdocjjang 그리고 탭따로따로 전부 분할하셔야합니다. 탭을 한개의 창에 탭만 다열어두시면 새로고침속도/로드속도가 느립니다. CPU리소스도 덜먹구요. 탭을 전부분리시켜 한화면에띄워놔야 빠릿하게되요

**Comment by changdocjjang** [comment]
> @changdocjjang 그리고 탭따로따로 전부 분할하셔야합니다. 탭을 한개의 창에 탭만 다열어두시면 새로고침속도/로드속도가 느립니다. CPU리소스도 덜먹구요. 탭을 전부분리시켜 한화면에띄워놔야 빠릿하게되요

아 몰랐습니다 조언 감사드립니다 분리하겠습니다

**Comment by changdoc** [comment]
저도 오늘 예약 시도를 처음 하게됐는데

예약 시도하여 오류 페이지(응답지연)
오류 페이지에 있는 새로고침 버튼 눌렀더니 실패 페이지로 이동
예약 시도 목록에도 실패로 확인되어..
실패됐구나 싶었는데

한5분 뒤에 문자로 예약 안내가 도착해서 지금 접종 하러 가는 중입니다

**Comment by changdoc** [comment]
저도 오늘 예약 시도를 처음 하게됐는데

예약 시도하여 오류 페이지(응답지연)
오류 페이지에 있는 새로고침 버튼 눌렀더니 실패 페이지로 이동
예약 시도 목록에도 실패로 확인되어..
실패됐구나 싶었는데

한5분 뒤에 문자로 예약 안내가 도착해서 지금 접종 하러 가는 중입니다
