### ISSUE TITLE
안녕하세요 제작자님

### ISSUE THREAD

**Issue by pingu980426** [changdoc/naver-vaccine-macro#18]
먼저 잔여백신 예약에 큰 도움을 주셔서 감사의 말씀 드립니다.

매크로가 적발될 시 처벌가능성 때문에 이용자들이 두려움이 있는 것 같네요. 물론 처벌가능성은 거의 없겠지만, 적발을 우회하는 방법이 있을 것 같아서 말씀드립니다. 매크로는 기본적으로 클릭 정보를 바탕으로 적발을 합니다. 1000ms를 주기로 거의 정확하고 일정하게 클릭을 한다면 매크로라고 인식을 하는 것이죠. 그러나 클릭 주기를 적절하게 난수화한다면 이를 우회할 수 있지 않을까 하는 생각이 듭니다. 물론 난수화를 해도 데이터가 쌓이면 정규분포 형태를 띄기에 적발 가능하지만, 이중 난수화를 한다면 이또한 우회 가능합니다.

이러한 점을 반영한다면 어떨까요?

**Comment by changdoc** [comment]
우선 클릭 이벤트는 백신 예약 가능할때 1회만 발생 시키고 있는 형태긴합니다.

새로고침 주기로 설정된 시간으로 페이지를 리로드 하는 형태로 동작중이긴합니다.
새로 고침 주기를 ms 단위로 조금씩 변화를 주는것도 실제 사람이 새로고침 하는 것과 같은 효과를 볼 수 있어 의미가 있을듯 하네요.

**Comment by changdoc** [comment]
https://github.com/changdoc/naver-vaccine-macro/commit/c10a9a5a6cd1186dc4dea76ed5f43d67e5b21a4c
새로고침 주기 적용할때 0~20ms씩 변화를 가하도록 적용해두었습니다.

**Comment by pingu980426** [comment]
감사합니다 제작자님. 좋은 하루 되세요!!
