### ISSUE TITLE
오류인줄 알았는데 작동됩니다

### ISSUE THREAD

**Issue by KimDomiz** [changdoc/naver-vaccine-macro#19]
제작자님 정말 감사합니다... 덕분에 성공적으로 예약한것 같습니다 감사합니다.

저도 몇번 계속 예약자수가 많다면서 실패하길래 안되는건가 했는데 뒤늦게 접종문자가 오더라구요 몇십분 뒤에 온것 같습니다.

**Comment by changdoc** [comment]
예약 성공하셨다니 다행입니다. 백신 접종 잘 하시고 건강하세요~!
