### ISSUE TITLE
네이버쪽에서 매크로를막은것같네요

### ISSUE THREAD

**Issue by JINHYUKJEONG** [changdoc/naver-vaccine-macro#2]
어제 최근일자 기사를보니 안티봇을 도입해서 무한 새로고침은 예약하는 과정을 넘어가지못하게 막는것같더라구요, 저도 소스를 보았지만 딱히 달라진점이 없는것같아서 아마 백엔드단에서 처리되게 했나싶기도한데..
제생각에는 새로고침대신 프록시를 거쳐서 초마다 직접백신데이터를 긁어오던가 아니면 매크로시도할 브라우저환경과 분리된 브라우저(프록시적용, 다른세션)를 새로 만들어서 따로 새로고침한후 감지되면 기존 브라우저로 정보를 넘겨서 한번만 새로고침을 하게하는방법이 있을것 같습니다. 이번주부터 쓰려고했더니 제능력밖의 일이생겼네요 ㅠ

++매크로 시작버튼도 안뜹니다

**Comment by changdoc** [comment]
https://news.mt.co.kr/mtview.php?no=2021070517302023951

제가 작업한 매크로는 지정한 병원 예약 페이지를 새로고침 하는 방식이라 괜찮을줄 알았는데... ㅠ

대응 가능한 방법이 있는지 한번 고민 해봐야겠네요.

**Comment by SJang1** [comment]
여기는 매크로 시작버튼은 뜨는데, 시작을 누르면 처음 한번만 새로고침된 후에 더이상 새로고침되지가 않네요.
<img width="545" alt="스크린샷 2021-07-06 오후 2 36 39" src="https://user-images.githubusercontent.com/29011440/124547804-ae2b4080-de67-11eb-9155-b98f2688633f.png">

**Comment by changdoc** [comment]
백신 종류 리스트 페이지 레이아웃이 바뀌어 새로고침 시도를 안하고 있어 수정 진행했습니다. 
https://github.com/changdoc/naver-vaccine-macro/commit/209b398875fe29c8258a531ab9484cea58e4d589

테스트로 돌리는 중인데 아직 잔여 백신 뜬 곳에선 테스트가 안되어서 예약까지 이루어지는지 검증이 안됐네요.

**Comment by JINHYUKJEONG** [comment]
빠른피드백과 업데이트 정말감사합니다! 질문하나있는데 인증서만 설치했으면 새로고침하고 백신수량나올때 따로 인증서로 인증할 필요는없죠?

**Comment by changdoc** [comment]
PC에서 최초로 예약 페이지 접근때만 인증서 요구를 하게 되는 것으로 알고 있어요. 한번 인증 수행했다면 백신 수량 뜰때는 별도로 인증 안하고 바로 예약 시도 하게 됩니다.

++Readme에 톡톡에서 메시지안오더라도 개발자도구에서 원하는 병원의 링크를 딸수있다고 적어주시는것도 도움될것같아요!
<-- 그렇네요. 개발자 도구로 원하는 병원 링크 따는 법 추가해두도록 하겠습니다.
