### ISSUE TITLE
빵빠레 소리가 들렸는데, 멈추지 않아요

### ISSUE THREAD

**Issue by kcharliek** [changdoc/naver-vaccine-macro#20]
안녕하세요 제작자님.
덕분에 수월하게 신청하고 있지만, 소득은 아직 없네요 ㅠㅠ
종종 빵빠레가 들리는데 신청이 멈추지 않네요.
혹시 정상동작하고있는지 알 수 있을까요?
네이버 백신 신청 이력에도 나오지 않아요.

확인 부탁드리겠습니다.
고맙습니다.

**Comment by massu850310** [comment]
빵빠레 나온 탭이 어느 탭인지를 확인하시고~ 
페이지에 새로고침 하라고 나와있는 경우, 새로 고침을 하시고

실패사유에

잔여백신 수량마감 (신청 이력 O, 예약 실패)
예약 실패 (신청 이력 X, 예약 실패)
질병관리청 응답지연 (신청 이력 X, 예약 성공 가능성 있음, 10분 뒤에 질병청에서 문자 오면 ㅇㅋ)
예약 확인 실패 (신청 이력 X, 예약 성공 가능성 있음, 10분 뒤에 질병청에서 문자 오면 ㅇㅋ)

전 현재 이렇게 4개 확인했습니다

**Comment by kcharliek** [comment]
빵빠레 나온탭에 새로고침도 안나오고, 실패사유도 나오지 않습니다.
빵빠레는 나왔는데, 변함없이 진행되고있어요.

**Comment by changdoc** [comment]
혹시 test mode가 체크되어 있진 않은지 확인 부탁드립니다.

체크가 해제되어 있어야 예약 신청을 시도하게 되어있습니다.

**Comment by changdoc** [comment]
test mode가 아닌데 빵빠레가 울렸지만 계속 시도중인거라면 에러 페이지 (네이버측 에러 페이지)가 노출되었을때도 울리게 되어 있어 그 상황일지도 모르겠네요.

**Comment by changdoc** [comment]
음.. 에러 페이지라 새로고침 하는데 재생중인 빵빠레는 안울리도록 빼두겠습니다. 혼돈을 줄 수 있겠네요

**Comment by changdoc** [comment]
https://github.com/changdoc/naver-vaccine-macro/commit/bd8c7163f5dbbb711715d95f18721043272d9770

예약 신청 페이지 자체에서 에러가 발생될 경우 사운드 재생 되지 않도록 수정해두었습니다.
