### ISSUE TITLE
left_count_by_coords api가 변경되었습니다

### ISSUE THREAD

**Issue by JINHYUKJEONG** [changdoc/naver-vaccine-macro#200]
left_count_by_coords api가 v2에서 v3로 변경되었네요.

**Comment by changdoc** [comment]
그러네요. spec은 바뀐게 없는 거 같아보여 우선 호출 url 변경해두었습니다.
https://github.com/changdoc/naver-vaccine-macro/commit/8d403f9ea6aadb40a3ad82e17be25eb4e7b6ca9d
