### ISSUE TITLE
개발자님 안녕하세요.

### ISSUE THREAD

**Issue by pingu980426** [changdoc/naver-vaccine-macro#21]
KTX 티켓팅 매크로를 바탕으로 만드셨다고 나와 있는데, 저도 CS 전공자로서 연습삼아 지도상에서 예약되는 익스텐션을 제작해 보려고 합니다. 혹시 관련해서 어떤 공부를 하셨나요? HTML CSS JS 등은 대충 알고 있는데 어렵네요 ㅠㅠ

**Comment by pingu980426** [comment]
추가로 서울 지역에 있는 병원들에 대해서 잔여백신 발생 빈도, 시간대 등을 패턴 분석을 하여 로그 형태로 만드는 것도 생각 중이었습니다.

**Comment by changdoc** [comment]
크롬 익스텐션으로 자체 서비스(서버 구성) 없이
뭔가를 제작할때 필요한건 말씀하신 html, css, js 지식이 전부 일 듯 하네요.

예전에 웹 개발을 진행해봤던 이력이 있어 따로 공부를 하진 않았고요.
만들면서 javascript, html 쪽에 필요한 부분들은 구글링해서 진행했습니다.

#4 여기 이슈 내의 graphql response를 직접 처리한다면 지도상에서 예약 되는 익스텐션도 제작은 가능 할 것으로 보이긴하네요.
