### ISSUE TITLE
현재 예약페이지로 접근이 막힌 것 같습니다.

### ISSUE THREAD

**Issue by hyunie88** [changdoc/naver-vaccine-macro#22]
기존의 url 추출 방법과 예약 목록 링크로 이동하는 방법 둘 다 접근이 안됩니다.

![w11](https://user-images.githubusercontent.com/70103279/125956703-564bc646-ecaf-4d67-801e-1494cf406a3e.JPG)

**Comment by changdoc** [comment]
그러네요. 대응 가능한지 확인해보도록 하겠습니다.

**Comment by changdoc** [comment]
예약 신청 페이지 접근 파라미터에 sid를 추가하여 정상 접근 되는 부분 확인했습니다.
https://github.com/changdoc/naver-vaccine-macro/commit/51e890950542a5bf1c4bf980771c691b082f172a

#4 추출 안내 페이지에도 sid추출하는 방법 추가 해두었습니다.

**Comment by hbkong** [comment]
이걸 뚫는다고..? 개발자님 멋있어요

**Comment by changdoc** [comment]
1.0.6 버전으로 수정사항 반영된 빌드 배포 해두었습니다. https://github.com/changdoc/naver-vaccine-macro/releases/tag/v1.0.6

**Comment by hyunie88** [comment]
앗 감사합니다.
