### ISSUE TITLE
크롬 네이버 인증서 저장 방법?

### ISSUE THREAD

**Issue by Yeaheyaheyah** [changdoc/naver-vaccine-macro#23]
안녕하세요 제작자님

네이버 인증서는 웨일 브라우저에만 저장할 수 있다고 하는데,
웨일 스토어에 백신 매크로 프로그램이 검색이 안 되더라고요.

크롬에 네이버 인증서를 저장할 수 있는 방법이 있나요?

**Comment by changdoc** [comment]
네이버 인증서를 저장할 필요가 없고 백신 예약 페이지에 최초 접근하게 되면 네이버 인증서를 통해 본인 인증을 1회 진행하는 형태입니다.

웨일 스토어에 등록 계획은 따로 없습니다.
