### ISSUE TITLE
맵 에서 백신 종류 구분해서 예약 시도 하도록 처리

### ISSUE THREAD

**Issue by changdoc** [changdoc/naver-vaccine-macro#238]
### Discussed in https://github.com/changdoc/naver-vaccine-macro/discussions/236

<div type='discussions-op-text'>

<sup>Originally posted by **rladbssam317** August  6, 2021</sup>
안녕하세요 개발자님! 좋은 파일 만들어 주셔서 감사합니다! 
네이버맵은 10분 정도 사용하면 graphql이 빨갛게 변해서 사용을 못하고 카카오맵을 사용하고 있습니다! 

질문이 두가지 있는데요 

1. F12 network에 left count도 정상적으로 fetch되고 있습니다. 그러나 분명 핸드폰으로는 잔여백신 알림 배너가 왔는데도 불구하고 카카오맵에서는 인식하지 못하였습니다. 왜 그러는걸까요? 인식되는 매커니즘이 어떻게 되는건지 궁금합니다. 지도상에 마감이라고 되어있으면 인식을 못하는건지, 아니면 단순 렉인건지 궁금합니다. 

2. 현재 4일동안 하고 있는데 어제 딱 한번 성공을 했어요. 근데 저희 부모님이 이미 아스트라로 예약이 되어있어서 중복예약 때문에 아쉽게 넘어갔습니다. 그래서 아스트라 우선 취소했어요. 우선 매크로가 잘 작동되고 있긴 한데 번번히 실패하고 있습니다. 혹시 여기서 예약 속도를 더 높일 수 있는 방법은 없나요? 저번에 어떤분이 500ms에서 250ms로 바꿧다고 했는데 시도해보았으나 똑같았습니다...  
</div>

**Comment by rladbssam317** [comment]
항상 감사합니다!

**Comment by changdoc** [comment]
https://github.com/changdoc/naver-vaccine-macro/releases/tag/v1.1.4

우선 네이버 맵에서
선택한 백신 종류의 잔여 수량을 파악하여 예약 신청 페이지로 넘어가도록 반영했습니다.

**Comment by HANUL2MERRY** [comment]
@changdoc 개발자님 아직 스토어 페이지엔 1.1.3이던데요~ 업데이트 시간은 조금 걸리는건가요?

**Comment by changdoc** [comment]
네 크롬 스토어는 구글 측에서 심사를 진행한뒤에 공개처리가 되는 프로세스라 시간이 좀 걸립니다. 최소 하루는 걸렸던거 같아 조금 전에 패치 등록을 해서 내일은 되야 스토어 버전을 사용하실 수 있을 것 같습니다.

https://github.com/changdoc/naver-vaccine-macro/issues/29
이 쪽 참고하셔서 여기서 받은 소스코드를 설치하시는 것도 방법입니다.

**Comment by changdoc** [comment]
크롬스토어에 1.1.4 반영되어 본건 close하겠습니다.
