### ISSUE TITLE
막힌것같아요

### ISSUE THREAD

**Issue by frogfrogy** [changdoc/naver-vaccine-macro#24]
잘못된 접근이라고만 나오네요..

**Comment by frogfrogy** [comment]
추가로 새로고침 주기나 백신 아무거나 탭에서 값을 바꿔도 다시 들어가면 적용이 안되는데
자세히 아시는 분 계실까요~?

**Comment by changdoc** [comment]
크롬 스토어에 최근 버전 등록 요청을 해두었으나 심사가 딜레이 되어 최신 버전을 바로 반영 못하고 있네요.

https://github.com/changdoc/naver-vaccine-macro/releases/tag/v1.0.6
1.0.6버전 받으시고 개발자 모드 활성화한 뒤 로드하셔서 진행 해보시겠어요?

**Comment by frogfrogy** [comment]
감사합니다 :)
