### ISSUE TITLE
생성된 병원 목록에서 원하는 병원을 지우는 기능을 추가할 수 있으면 좋겠습니다.

### ISSUE THREAD

**Issue by loolsasy** [changdoc/naver-vaccine-macro#245]
아스트라제네카는 잔여백신이 꽤 많이 나오고 있는데요.
맵에 등록한 병원에서 아스트라제네카가 올라오면 해당 병원 예약 페이지로 이동합니다.
그런데 저는 나이가 42라서 아스트라제네카는 예약할 수 없습니다.

다시 맵으로 돌아가서 자동 새로고침을 돌리면 잔여백신이 있으니 해당 예약페이지로 다시 이동하는걸 반복하게됩니다.
맵에서 원하는 백신을 선택할 수 있으면 좋겠지만 그게 어렵다면 등록한 병원 목록에서 선택한 목록을 제거할 수 있는 기능을 추가할 수 있으면 좋겠습니다.

**Comment by changdoc** [comment]
아하 AZ가 많이 풀려서 현재 지도에서 동작시키는 부분이 무의미해졌네요;
수정 방안을 마련해보도록 하겠습니다.

**Comment by loolsasy** [comment]
감사합니다.
참고로 저는 예약 성공해서 프로그램을 더 돌릴필요는 없네요. ㅎㅎㅎ

**Comment by changdoc** [comment]
https://github.com/changdoc/naver-vaccine-macro/releases/tag/v1.1.4

우선 네이버 맵에서
선택한 백신 종류의 잔여 수량을 파악하여 예약 신청 페이지로 넘어가도록 반영했습니다.


예약 성공 하셨다니 다행입니다. 이 이슈는 클로즈하겠습니다.
