### ISSUE TITLE
 AZ 물량이 쏟아져나오고 있어서 스크리닝이 필요

### ISSUE THREAD

**Issue by rladbssam317** [changdoc/naver-vaccine-macro#246]
AZ가 많아져서 예약페이지로 계속해서 이동하고 있습니다! 

잔여백신이 생겼을 때 예약페이지로 넘어가기전에 모더나나 화이자인지 확인하고 예약페이지로 넘어가게 수정이 가능할까요 개발자님?

**Comment by changdoc** [comment]
https://github.com/changdoc/naver-vaccine-macro/releases/tag/v1.1.4

우선 네이버 맵에서
선택한 백신 종류의 잔여 수량을 파악하여 예약 신청 페이지로 넘어가도록 반영했습니다.

**Comment by rladbssam317** [comment]
감사합니다! 아직 카카오맵에서는 적용은 좀 더 기다려야되죠?

**Comment by changdoc** [comment]
네 카카오맵 쪽은 백신 종류 판단을 하려면 추가 api연동이 필요할 것 같아 적용하는데 시간이 좀 더 필요할것 같습니다.

**Comment by changdoc** [comment]
카카오쪽도 적용진행했습니다만 병원별로 조회를 해야해서 카카오 인증 진행 후 매크로 동작해야하는 형태로 반영했습니다. 
관련 가이드는 업데이트 해두었습니다. https://github.com/changdoc/naver-vaccine-macro/issues/166

https://github.com/changdoc/naver-vaccine-macro/commit/fcf6d25fd784a46bb192ae680188dcaf9c1fec0b
아직 테스트를 제대로 못해봐서 테스트 진행되는 대로 버전 release해두겠습니다.

**Comment by changdoc** [comment]
https://github.com/changdoc/naver-vaccine-macro/releases/tag/v1.1.5

카카오맵도 백신 선택시 선택한 백신 잔여 수량이 탐지될때 동작하도록 수정했습니다.

본 건 close 합니다.
