### ISSUE TITLE
1.0.4버전 빵빠레울리면서 오류 라고뜹니다

### ISSUE THREAD

**Issue by oKaKao** [changdoc/naver-vaccine-macro#25]
혹시 제가 뭘 잘못하고있거나
다음버전을 기다려야 할까요?

추가적으로 만들어주셔서 감사합니다 :)

**Comment by changdoc** [comment]
빵빠레가 울렸다는건 잔여 백신이 발생해서 예약 시도를 수행했다고 볼 수 있습니다.
매크로 버전과는 무관합니다.

오류가 뜬건 예약 시도 하는 사람들이 동시에 몰려서 질병 관리청에서 빠른시간내에 응답을 주지 못해도 발생합니다. (저도 예약 성공 케이스에 오류 페이지가 떴었습니다.)

예약이 성공되었다면 수 분 내로 문자로 안내 메시지가 오게되고
실패가 되었다면 별도로 연락이 오지 않을 거에요.
