### ISSUE TITLE
예약창에서 바로 예약이 안됩니다.

### ISSUE THREAD

**Issue by hongkoo** [changdoc/naver-vaccine-macro#259]
12일 오전 10시부터 갑자기 예약창 모양이 바뀌면서 바로 예약이 안됩니다.

**Comment by changdoc** [comment]
예약 버튼이 사라졌다는 말씀이실까요?
https://github.com/changdoc/naver-vaccine-macro/discussions/257

**Comment by leeum2** [comment]
> 예약 버튼이 사라졌다는 말씀이실까요?
> #257

네 자동예약시작 버튼을 누르면 사라집니다

**Comment by changdoc** [comment]
https://github.com/changdoc/naver-vaccine-macro/releases/tag/v1.1.6

1.1.6 버전으로 시도해주세요

**Comment by hongkoo** [comment]
넵 이제 작동하네요
