### ISSUE TITLE
graphql 들어간 뒤 로딩 오류

### ISSUE THREAD

**Issue by chennysongg** [changdoc/naver-vaccine-macro#26]
![Screen Shot 2021-07-17 at 9 58 49 PM](https://user-images.githubusercontent.com/56359954/126037805-75ae1dd1-528c-48ec-9345-e5cb916165e0.png)

개발자님 안녕하세요! 다름이 아니라 graphql에 들어간 후 계속 failed to load response data라고 뜨는데 혹시 여기서 어떻게 해야하는지 아시나요?? 컴퓨터가 문제인가 싶어 다른 컴퓨터로도 다 해봤는데도 똑같이 떠서 질문드립니다 ㅠㅠ

**Comment by changdoc** [comment]
graphql 통신 이력이 여러개로 노출이 되고 있을텐데요. 정상적으로 응답 받은 이력이면 정상적으로 노출되게 됩니다.
제가 response 값 볼때 수행하는 모습 캡쳐로 올리겠습니다.

**Comment by changdoc** [comment]
![Jul-17-2021 23-29-31](https://user-images.githubusercontent.com/1879494/126040232-6ced5ea3-4cf3-4e9f-a0da-cd95a37a9f1c.gif)

데이터 확인하실때 status가 200인 필드를 누르시면 됩니다.
<img width="418" alt="스크린샷 2021-07-17 오후 11 30 49" src="https://user-images.githubusercontent.com/1879494/126040258-c044a540-eb93-415a-9eb7-88c2db9290ea.png">

**Comment by chennysongg** [comment]
감사합니다!!!
