### ISSUE TITLE
화이자백신 선택이 안되는 것 같아요.

### ISSUE THREAD

**Issue by bonjourandy** [changdoc/naver-vaccine-macro#263]
예약신청 사이트에서 해당 병원에 화이자 또는 모더나 백신이 떳을 때 병원이 보유한 (현재 물량이 남아도는) AZ 잔여백신이 자동선택 되어 예약신청이 눌러지나 봅니다. 나이가 맞지 않아 예약이 불가하다고 뜨는데 해결 방법이 있을까요. 감사합니다.

**Comment by bonjourandy** [comment]
정말 죄송하지만 해당 해당 옵션창은 어디로 들어가면 볼 수 있나요? 현재 이 창에서 매크로 중입니다.
![제목 없음](https://user-images.githubusercontent.com/88814308/129136999-efcbcc20-36e3-4f01-ac3b-b7de03305ea4.jpg)

**Comment by DeokhunKim** [comment]
> 정말 죄송하지만 해당 해당 옵션창은 어디로 들어가면 볼 수 있나요? 현재 이 창에서 매크로 중입니다.

크롬 확장프로그램을 실행시키면 나옵니다

**Comment by bonjourandy** [comment]
아 혹시 확장프로그램에 있는 popup파일인가요?

**Comment by bonjourandy** [comment]
아 찾았습니다.. 제대로 찾아보지도 않고 글 올렸네요 ㅠㅠ 핑프짓 죄송합니다.
