### ISSUE TITLE
잔여백신 발생시 멈춤 관련

### ISSUE THREAD

**Issue by hyunie88** [changdoc/naver-vaccine-macro#27]
![unnamed](https://user-images.githubusercontent.com/70103279/126053381-ef78cd34-6e38-4d1a-b86a-9b0fe6399f9c.png)

안녕하세요. 1.0.6 버전 이후로 보이는 멈춤 현상이 발생되는 것 같아 남깁니다.
이전 같은 경우에는 백신을 놓치는 경우가 있더라도 
잔여 백신이 발생되면 거의 99% 이상으로 일단 캐치는 했었던 것 같습니다.

근데, 1.0.6 버전 이후로 해당 캡쳐 처럼 자동 새고하던창이 저 상태에서 계속 멈춰있는 현상이 보입니다.
다른 탭에 켜놓은 타 병원들은 정상적으로 작동중입니다.
그 시점이 늘 잔여 백신 발생 전후인 것 같아 확인 요청드립니다.

+ 혹시 텔레그램 메세지 발송시 시도했던 병원명이 같이 기재되도록 수정해주실 수 있을지요?

**Comment by hyunie88** [comment]
잔여백신 수량 오류난 페이지가 있어서 여러번 시도를 해봤는데
그냥 직접페이지를 눌러서 들어갔을 때도 위에 캡쳐처럼 수량이 없는걸로 나오는데
계속해서 잔여 수량은 있다고 표기가 됨

에프5 누르면서 봤을 때 페이지 로딩 과정에서 잠깐 화이자+수량이 표기되는데  로딩완료 시점에는 다시 백신없음표기

새로고침을 열번 이상 했을 때 한 번정도 나타나거나 잠깐 표기될 때 그 부분 백신 선택을 하게되면 밑에 신청 버튼이 활성화되네요.

말로 설명이 되었는지 모르겠어요;;

**Comment by hyunie88** [comment]
위에 현상이 확장을 아예 껐을 때는 정상적으로 잔여수량 + 신청페이지가 활성화됩니다.

**Comment by IAmEnchant** [comment]
```js
// reservationInfo.js
var e = atob("a3R4LW1hY3JvLWJ1dHRvbg==") // e = ktx-macro-button
              , t = document.getElementsByClassName(e).length > 0;
            if (navigator.webdriver || t)
                return $("#info_item_exist").css("display", "none"), // 백신 목록 숨김
                $("#info_item_empty").css("display", "block"),       // 백신 소진 노출
                void function(e) {
                    new U("/api/log?type=" + e).post().then((function() {}
                    )).catch((function() {}
                    ))
                }(navigator.webdriver ? "webdriver" : "chrome_extension");
```

위 자바스크립트 코드는 네이버 백신 예약 페이지의 스크립트인데,
네이버 측에서 이 확장 프로그램이나 크롬 자동화 프로그램을 이용하여
예약 페이지에 진입 시 잔여 수량을 숨겨놓는 업데이트를 한것으로 파악됩니다.
또한 프로그램 사용 시 네이버에서 로그를 수집하고 있는데 어떻게 사용될진 모르겠네요.

**Comment by DI-LEE** [comment]
그럼 이제 못쓰게 된건가요? ㅠ

**Comment by Kim-Dong-Hyeon** [comment]
@IAmEnchant

네이버 백신 예약 페이지 스크립트가 이렇게 바꼈다는 얘기는 
요기 깃허브도 이미 네이버 개발자 분이 보고계시다는 얘기네요 ㅎ
ktx-macro-button folk 해서 만들어주신 매크로는 요기밖에 없을텐데.. 완전 집중 마크한거 같은 느낌이 드네요 >.<

**Comment by Kim-Dong-Hyeon** [comment]
@IAmEnchant

네이버 백신 예약 페이지 스크립트가 이렇게 바꼈다는 얘기는 
요기 repository도 이미 네이버 개발자 분이 보고계시다는 얘기네요
ktx-macro-button folk 해서 만들어주신 매크로는 요기밖에 없을텐데.. 완전 집중 마크한거 같은 느낌이 드네요 >.<

**Comment by changdoc** [comment]
@IAmEnchant 제보 감사합니다. 전혀 모르고 있어네요. atob 로 인코딩해서 매크로가 생성하는 버튼이 있는걸 탐지 하는 형태로 하고 있었네요.
로그를 남기는거 보면 매크로 사용 유저들을 따로 기록하고 있을것으로 예상됩니다.

정책적으로나 추후에 문제가 될때 해당 로그 데이터들이 활용 될 가능성이 있겠군요;

**Comment by changdoc** [comment]
@hyunie88 제보해주신 증상과 텔레그램 메시지에 병원 이름 포함되도록 하는 버전 배포해두었습니다.

https://github.com/changdoc/naver-vaccine-macro/releases/tag/v1.0.7

**Comment by hyunie88** [comment]
감사합니다!

**Comment by changdoc** [comment]
테스트로 돌려보는 중인데 결과 페이지로 이동 되면서 병원 이름 저장해둔게 유지가 안되는 형태라
메시지에 포함이 안되고 있네요; 

예약 시도 시점에 병원 이름 포함되도록 추가해봤습니다.
https://github.com/changdoc/naver-vaccine-macro/commit/84bcd18b1dc4bb70bfa738e4a949351f4bd43a85

**Comment by H4NJ1N** [comment]
현재 새로고침은 되는데 자동으로 예약을 안하는데 맞나요?

**Comment by changdoc** [comment]
@H4NJ1N 잔여 백신이 발생했을때 예약 시도가 안됐다는 말씀이실까요?

**Comment by H4NJ1N** [comment]
> @H4NJ1N 잔여 백신이 발생했을때 예약 시도가 안됐다는 말씀이실까요?

맞습니다. 크롬으로 시도 중이고 1.0.7 버전입니다. 백신이 발생할 때까지 새로고침은 성공하는데 계속 예약을 안 누릅니다.

**Comment by OneTop4458** [comment]
개인적인 의견이지만 atob로 대놓고 ktx-macro-button을 탐지한다면
저희도 버튼 이름을 랜덤으로 출력되게 대응해보면 어떨까 싶네요

**Comment by changdoc** [comment]
@H4NJ1N 오전에 확인할때까지 정상이였는데요.
개발자 도구 열어서 console 탭을 두시고 백신 발생할때 어떤 에러 로그가 발생하는지 공유 해주실 수 있을까요?

**Comment by H4NJ1N** [comment]
> @H4NJ1N 오전에 확인할때까지 정상이였는데요.
> 개발자 도구 열어서 console 탭을 두시고 백신 발생할때 어떤 에러 로그가 발생하는지 공유 해주실 수 있을까요?

백신 발생하면 올리겠습니다.

**Comment by H4NJ1N** [comment]
![DDF0E625-19E1-4031-BB28-58308B2D68DC](https://user-images.githubusercontent.com/72609275/126108898-f3c183a3-d59a-4b98-9a12-6cfb72614a6a.jpeg)
백신은 발생했는데 예약신청하지 않습니다.

**Comment by OneTop4458** [comment]
@H4NJ1N 혹시 크롬 확장 프로그램이 깔려있나요
아님 웨일 브라우저가 실행 중 이라던가

저도 구 버전에서 동일 현상 있었는데
크롬 확장 프로그램 다 지우고 백신 매크로만 남겨두고
웨일 제거하니 정상 작동했습니다.

**Comment by H4NJ1N** [comment]
> @H4NJ1N 혹시 크롬 확장 프로그램이 깔려있나요
> 아님 웨일 브라우저가 실행 중 이라던가
> 
> 저도 구 버전에서 동일 현상 있었는데
> 크롬 확장 프로그램 다 지우고 백신 매크로만 남겨두고
> 웨일 제거하니 정상 작동했습니다.

오늘 웨일 실행한 적은 있습니다. 현재는 실행중이지 않구요.. 확장프로그램 설치 되어있던 거 전부 삭제후 다시 진행중입니다.

**Comment by changdocjjang** [comment]
저도 방금 잔여백신은 발생했으나
예약시도 안했습니다

**Comment by OneTop4458** [comment]
> > @H4NJ1N 혹시 크롬 확장 프로그램이 깔려있나요
> > 아님 웨일 브라우저가 실행 중 이라던가
> > 저도 구 버전에서 동일 현상 있었는데
> > 크롬 확장 프로그램 다 지우고 백신 매크로만 남겨두고
> > 웨일 제거하니 정상 작동했습니다.
> 
> 오늘 웨일 실행한 적은 있습니다. 현재는 실행중이지 않구요.. 확장프로그램 설치 되어있던 거 전부 삭제후 다시 진행중입니다.

웨일 아예 제거 또는 웨일 확장 전부 제거 후 실행 해보세요.. 
뭔가 웨일 확장이랑 충돌 나서 웨일 안켜도 설치만 되있어도 저런 경우도 있더라구요

**Comment by changdoc** [comment]
네이버 페이지 자체에 변동 사항이 있었나 보네요. 저도 확인해보고 다시 수정해보겠습니다.

**Comment by H4NJ1N** [comment]
> > > @H4NJ1N 혹시 크롬 확장 프로그램이 깔려있나요
> > > 아님 웨일 브라우저가 실행 중 이라던가
> > > 저도 구 버전에서 동일 현상 있었는데
> > > 크롬 확장 프로그램 다 지우고 백신 매크로만 남겨두고
> > > 웨일 제거하니 정상 작동했습니다.
> > 
> > 
> > 오늘 웨일 실행한 적은 있습니다. 현재는 실행중이지 않구요.. 확장프로그램 설치 되어있던 거 전부 삭제후 다시 진행중입니다.
> 
> 웨일 아예 제거 또는 웨일 확장 전부 제거 후 실행 해보세요..
> 뭔가 웨일 확장이랑 충돌 나서 웨일 안켜도 설치만 되있어도 저런 경우도 있더라구요

재부팅 웨일 삭제 후 재실행 중입니다

**Comment by chennysongg** [comment]
저도 아까 잔여백신 떴는데 예약 시도가 자동으로 안 되더라고요 😭

**Comment by changdocjjang** [comment]
지금도 잔여백신이 있는데 예약진행을 안하고 가만히 있습니다
콘솔에서 뭘 보여드릴까요 제작자님

**Comment by changdoc** [comment]
console에 에러가 없는걸로 봐서는 에러는 아닌거 같고

**Comment by changdoc** [comment]
우클릭 눌러서 페이지 소스 보기 해서 내용을 보여주실 수 있을까요?

**Comment by changdoc** [comment]
![image](https://user-images.githubusercontent.com/1879494/126111643-89617d26-251b-417c-af1f-1de2a525db96.png)
예약 신청 이쪽에 변화가 있을것으로 예상이 됩니다.

**Comment by changdocjjang** [comment]
넵 또 멈추면 페이지소스올려드릴게요

**Comment by asdfqawehf** [comment]
![image](https://user-images.githubusercontent.com/87635367/126112658-dcd947ea-f7c5-4b07-ab7a-d5096362a869.png)

**Comment by asdfqawehf** [comment]
![image](https://user-images.githubusercontent.com/87635367/126112781-48f1bbdd-95e3-414e-bd47-1e4f070aeb03.png)
이 부분도

**Comment by changdoc** [comment]
클릭 이벤트가 동작을 안하는거 같네요.
url 이동 방식으로 변경한 부분 올려뒀습니다.

**Comment by changdoc** [comment]
https://github.com/changdoc/naver-vaccine-macro/commit/95a47afabec29351ced5983a50d65feb032452bd

**Comment by DI-LEE** [comment]
기존1.07버전삭제하고 다시 1.07버전 다운받으면 되나요?

**Comment by changdoc** [comment]
버전도 올려두겠습니다.

**Comment by DI-LEE** [comment]
정말 감사합니다..ㅜ

**Comment by changdoc** [comment]
1.0.8로 예약 시도 방식 변경한 버전 배포해두었습니다.
https://github.com/changdoc/naver-vaccine-macro/releases/tag/v1.0.8

**Comment by H4NJ1N** [comment]
정상 작동합니다.

**Comment by changdocjjang** [comment]
예 노쇼 발생해도 이제 멈추지는 않습니다

**Comment by gingno** [comment]
앞으로는 그러면 사용하기가 힘들까요?

**Comment by changdoc** [comment]
네 사용불가 하다고 보셔야할 것 같습니다..
