### ISSUE TITLE
필터가 생겼습니다.

### ISSUE THREAD

**Issue by hyunie88** [changdoc/naver-vaccine-macro#278]
![dd](https://user-images.githubusercontent.com/70103279/130536570-dcddba5f-0b73-4207-95f7-c4e77ccb1131.PNG)

지도 부분에 필터 생기면서 변경되어 현재는 작동이 안됩니다.

**Comment by changdoc** [comment]
https://github.com/changdoc/naver-vaccine-macro/commit/3f761e7ace5a2dadf615aeaf52a5b51863f1bade
네이버 플레이스 잔여 백신 페이지 구조가 바뀌어서 대응 코드 추가했는데요.. 데이터 추출하는 부분도 좀 바뀌어서 가이드를 새로 작성해야할 듯하네요.

**Comment by changdoc** [comment]
<img width="1934" alt="스크린샷 2021-08-26 오후 5 45 53" src="https://user-images.githubusercontent.com/1879494/130931906-bb940652-fc16-4b91-bf89-d50dc8d9fe02.png">
