### ISSUE TITLE
잘못된 접근입니다

### ISSUE THREAD

**Issue by changdocjjang** [changdoc/naver-vaccine-macro#28]
병원목록 추출 후 접속 시 잘못된 접근이라고 하면서
페이지 자체를 막습니다 제작자님
저만 그런가요

**Comment by changdoc** [comment]
#22 내용과 코멘트 보시면 url검증이 추가되어 패치를 진행했습니다

Release에 있는 1.0.7 버전으로 확인해주세요.

**Comment by changdocjjang** [comment]
아 네 감사합니다

**Comment by koolingo** [comment]
저도 병원목록 추줄 후 접속하면 잘못된 접근이라고 나오는데요.
Release된 1.0.7 버전으로  어떻게 변경(업데이트) 하는지 잘 모르겠습니다.

크롬에서 NAVER Vaccine MACRO 개발자 모드로 들어가서 업데이트 클릭하면 되는건가요?
그렇게 해도 최신버젼으로 적용이 안되는것 같습니다. 
새로운 버젼으로 업데이트 하는 방법좀 알려주시면 감사하겠습니다 
꼭 좀 부탁 드릴께요 개발자님! ㅠㅠ

**Comment by changdoc** [comment]
@koolingo #29 최신 코드(특정버전) 다운 받아서 크롬에 적용하는 방법 가이드 문서 업데이트해두었습니다. 참고해주세요.
