### ISSUE TITLE
Feature Request: 특정 페이지 도착 시 버튼을 누를 필요 없이 자동실행

### ISSUE THREAD

**Issue by SJang1** [changdoc/naver-vaccine-macro#3]
특정 페이지 (https://v-search.nid.naver.com/reservation/info?key=XXXX)에 도달하면 사용자가 중단을 누르기 전까지는 별다른 안내 없이 자동으로 시작되게 하는 기능을 추가하는것을 건의합니다.

버튼을 지금은 두번 눌러줘야 시작하는데 이미 백신이 있을때 들어가면 바로 백신예약을 시도하는게 성공확률을 올릴 수 있을 것이란 생각입니다.

**Comment by changdoc** [comment]
현재 작성되어있는 매크로 on/off 판단하는게 local storage에 저장 시켜둔 형태라서요.
어디서든 한번 켜두면 예약 대기 페이지에 온 뒤 잔여 백신이 있다고 판단되면 바로 예약 시도하는 형태로 동작중이긴합니다.

옵션으로 페이지 접근시 자동 시작 되는 부분도 추가할 수 있도록 검토 해보겠습니다.

**Comment by changdoc** [comment]
어디서든 한번 자동 예약 시도해두고 이후에는 예약 시도 url접근시 자동으로 수행되므로 명시적으로 사용자가 예약 시작 시점을 인지할 수 있는 현재 스펙을 유지해야 할 것 같습니다.

이슈는 close하겠습니다.
