### ISSUE TITLE
네이버 인증서 및 알림 신청 관련

### ISSUE THREAD

**Issue by 2021hanwoo** [changdoc/naver-vaccine-macro#31]
네이버 인증서 및 알림 신청을 하려고 하면 네이버 앱으로만 진행이 가능하다고 팝업이 뜹니다.

네이버 인증서는 웨일 브라우저의 모바일 창으로 실행하면 컴퓨터에 설치가 가능하긴 한데 알림 설정은 어떻게 하는지 모르겠습니다. 도와주세요 ㅜㅜㅜ

**Comment by massu850310** [comment]
본인인증 용도로 사용하는 네이버 인증서이며
말 그대로 휴대폰으로 네이버 앱 설치하시고 인증서 받으셔야
잔여백신 신청할 때 본인인증이 빠릅니다

휴대폰 본인인증으로 하셔도 무방한데, 인증서가 더 빨라요~

**Comment by 2021hanwoo** [comment]
자동 예약 신청 버튼이 보이는데 설치가 완료된건가요? 이 이후로는 매크로가 자동으로 예약해주는건가요??
