### ISSUE TITLE
잔여 발생시 예약시도까지는 되나 예약실패시 페이지가 멈추고 자동이 풀립니다

### ISSUE THREAD

**Issue by changdocjjang** [changdoc/naver-vaccine-macro#32]

**Comment by THePhanT00M** [comment]
예약 시도 후에는 다시 시도 할 경우 사용 방법 4번째 항목에 있는 [지금 신청 하기] 링크를 눌러 이동 하는 스텝 부터 다시 수행해야합니다.

**Comment by changdoc** [comment]
예약 시도 시점에 매크로 동작은 멈추게 되어 있습니다. 
실패 이후에 계속 해서 시도해서 다른 예외 상황을 발생하지 않게 하기 위해서 계속 수행 되지 않도록 해두었네요.

재시도 할 경우
시도하셨던 병원 예약 신청 페이지를 다시 여시고
다른 열려 있는 페이지들을 새로고침 수행해주셔야합니다.
