### ISSUE TITLE
자꾸 실패를 하는데 어떤걸 바꿔야할까요..?

### ISSUE THREAD

**Issue by dudma123** [changdoc/naver-vaccine-macro#33]
실행을 해놓으면 자동으로 새로고침을 계속하면서 작동이 됩니다
근데 막상 잔여백신이 나오면 아예 접속조차 못할때도있고 접속을해도 실패를합니다
창을 5개를 따로 띄어놓고 속도는 500~700까지 해봤는데 같네요..

이럴때는 어떤방법이 있을까요...? 크롬말고 다른걸 써야할까요?

**Comment by changdoc** [comment]
아예 접속을 못한다는게 에러 페이지가 나오는 상황일까요? (질병관리청 응답 지연 등의 메시지가 있는)
그렇다면 따로 하실 수 있는게 없을거 같습니다. 신청이 동시에 몰려 처리가 늦어지면서 서버가 응답을 느리게 하는 상황이라서요.

본 매크로는 크롬 확장 프로그램으로 작성된거라 크롬, 네이버 웨일 브라우저에서만 동작합니다.

**Comment by dudma123** [comment]
> 아예 접속을 못한다는게 에러 페이지가 나오는 상황일까요? (질병관리청 응답 지연 등의 메시지가 있는)
> 그렇다면 따로 하실 수 있는게 없을거 같습니다. 신청이 동시에 몰려 처리가 늦어지면서 서버가 응답을 느리게 하는 상황이라서요.
> 
> 본 매크로는 크롬 확장 프로그램으로 작성된거라 크롬, 네이버 웨일 브라우저에서만 동작합니다.

에러페이지는아닙니다 새로고침은 잘되는데 예약버튼을 잘 못누르거나 안눌리는것 같습니다!
혹은 눌러도 느리게 눌러서 예약에 실패하는것같습니다
혹시 방법이있을까요....?

**Comment by thsdlswo** [comment]
혹시 와이파이를 사용중이시다면 유선으로 연결해보세요.
아무래도 지금은 매크로끼리 경쟁이라 봐야하다보니 핑이 낮을수록 유리할꺼에요.
유선 사용중인데도 그런거라면 인터넷 환경 좋은곳에서 시도해보시는게 어떠신가요?

**Comment by changdoc** [comment]
크롬 스토어에서 받은 버전 사용중이시라면 예약 시도가 안되고 있을텐데요.

https://github.com/changdoc/naver-vaccine-macro/issues/29
여기 참고하셔서 최신 버전으로 사용부탁드립니다.

**Comment by dudma123** [comment]
> 으로 열어두지 마시고 하나하나 분리해서 창 띄워두시는

혹시 속도를 500이하로 설정하는것도 도움이될가요?

**Comment by thsdlswo** [comment]
> 
> 
> > 으로 열어두지 마시고 하나하나 분리해서 창 띄워두시는
> 
> 혹시 속도를 500이하로 설정하는것도 도움이될가요?

500이하로 설정해봤자 큰 의미는 없을꺼 같습니다.
(네이버쪽에서는 이런경우가 많아지면 서버 무리간다고 싫어할수는 있겠네요.)
