### ISSUE TITLE
타 매크로 댓글입니다 

### ISSUE THREAD

**Issue by changdocjjang** [changdoc/naver-vaccine-macro#35]
![image](https://user-images.githubusercontent.com/87104616/126241963-3107e486-38ef-490f-8ff3-bdf73c418f7a.png)

**Comment by OneTop4458** [comment]
여기 README.md 내용 복붙 같네요..

**Comment by changdoc** [comment]
본건은 논의할 내용이 없는거 같아 close하겠습니다.
