### ISSUE TITLE
브라우저별로 별도로 실행되었으면좋겠습니다.

### ISSUE THREAD

**Issue by JINHYUKJEONG** [changdoc/naver-vaccine-macro#5]
여러 병원을 동시에 돌리려 하다보니 lcoal저장소에서 실행상태를 공유하다보니까 기존에 실행하던창을 냅두고 다른창에서 시작하려고하면 기존창이 정지되버리네요 ㅠ

**Comment by changdoc** [comment]
![Jul-06-2021 19-01-46](https://user-images.githubusercontent.com/1879494/124582089-a7fb8b00-de8c-11eb-8d96-db9de91b012b.gif)

실행 상태가 공유가 되어서 첫번째 신청 페이지에서 실행 시키면
두번째 신청 페이지도 자동으로 동작하는 상태가 될텐데요.

둘다 페이지 접속해둔 상태라면 두번째 페이지는 새로고침 하시면 동작 할거에요.

**Comment by JINHYUKJEONG** [comment]
기존페이지들을 열어두고 실행시킨거라 새로고침을 안해서 작동이 안되었었군요.. 감사합니다
