### ISSUE TITLE
크롬에서는 업데이트 반영이 안된걸까요

### ISSUE THREAD

**Issue by hyunie88** [changdoc/naver-vaccine-macro#6]
검색해보다가 여기까지 들어오게되었는데
크롬은 6월22일자 업데이트로 되어있어서요!

**Comment by changdoc** [comment]
https://github.com/changdoc/naver-vaccine-macro/issues/2
이쪽 이슈 내용 보시면 네이버에서 매크로 대응을 하면서 일부 페이지(html) 레이아웃을 변경해서 현재 크롬에 공개된 버전은 매크로가 동작하지 않고 있는데요.

제가 확인 중인 동네 병원에서는 잔여 백신 발생이 하루에 한번 발생할까 말까해서 수정한 버전이 예약시도까지 정상적으로 수행하는지 검증이 안되어 아직 패치를 못하고 있는 상황입니다.

수정 확인이 되어 패치진행하게 되면 본 이슈에 코멘트로 공유해 드리겠습니다~

**Comment by hyunie88** [comment]
수정해주신 버전으로 실행해봤는데 잔여백신 알람은 와있는 병원에 못잡은건지 안잡힌건지 계속 새로고침으로 돌아가고있네요.

**Comment by hyunie88** [comment]
감사합니다! 방금 예약 성공했는데 예약창에는 예약확인실패 라는 메세지가 함께 떴는데 병원에서는 정상 예약됐다고 연락이 왔습니다.

**Comment by changdoc** [comment]
예약이 정상적으로 수행되었다니 다행이네요. 

백신 잘 맞으시고 건강하세요~!

**Comment by JINHYUKJEONG** [comment]
질병관리청이 폭주하어 오류가발생하였습니다. 자세한문의는 xx병원(전화번호) 나왔는데 전화한번해봐야하는건가여 ㅋㅋ

**Comment by JINHYUKJEONG** [comment]
![Screenshot_20210707-145709_Telegram](https://user-images.githubusercontent.com/17464885/124717106-c40c3480-df3f-11eb-8b27-b9a74fbbe722.jpg)
병원 10곳정도 돌리는데 오류나네요자꾸..ㅋㅋ(테스트안켰습니다)

**Comment by hyunie88** [comment]
+ 오류 화면이지만 정상적으로 예약은 됐음. 다만, 네이버에 신청 현황에는 아예 흔적이 없어요. 참고 부탁드립니다.

**Comment by changdoc** [comment]
> ![Screenshot_20210707-145709_Telegram](https://user-images.githubusercontent.com/17464885/124717106-c40c3480-df3f-11eb-8b27-b9a74fbbe722.jpg)
> 병원 10곳정도 돌리는데 오류나네요자꾸..ㅋㅋ(테스트안켰습니다)
> 
> ++ 오류는났지만 병원에서 전화와서 화이자 맞았습니다! 정말감사드립니다 ㅠ

우선 예약 성공하셨다니 다행입니다! 건강하세요~!

**Comment by changdoc** [comment]
화면 오류이고 내역에 흔적이 없는 부분은 제가 예약 시도할때 페이지 변동이 있는지 확인 해봐야겠네요.

@hyunie88 @JINHYUKJEONG 

제보 감사합니다~!

**Comment by changdoc** [comment]
크롬 스토어에 1.0.1 버전으로 공개되어 본건 close합니다.
