### ISSUE TITLE
크롬 7월 7일 버전 말고 다른 것을 다운받아야 하나요 제작자님?

### ISSUE THREAD

**Issue by changdocjjang** [changdoc/naver-vaccine-macro#7]
병원 숫자를 찾아도 정상적인 접근이 아니라고 예약창으로 못가는데
밑 분들은 어떻게 10군데 돌리시는지도 궁금 합니다
여기 사이트에서 신규 버전을 받아야하나요?

**Comment by changdocjjang** [comment]
아 제가 병원 숫자 찾는 것은 착각했네요 방법 알려주신대로 하니 페이지까진 정상 연결됩니다

크롭앱으로 다운 말고 다른곳에서 프로그램 다운 받아야하나요?

**Comment by changdoc** [comment]
크롬 웹스토어에 동작 버전은 심사 대기 중이라 조금 기다리셔야할것 같습니다.

개발자 모드로 적용가능하시면
https://github.com/changdoc/naver-vaccine-macro/releases/tag/1.0.1
서 받은 zip으로 설치하시면 됩니다.

**Comment by changdocjjang** [comment]
네 안그래도 크롭앱에 제작자님이 수정한 스트립트 교체하니
복구 필요하다면서 앱 사용이 안되네요
크롬을 개발자모드로 돌리고 받은 zip을
크롬 앱 디렉토리에 넣으란 말씀이시죠?

**Comment by changdocjjang** [comment]
말씀대로 개발자 모드 돌린 후
zip 다운 받으니 잘 실행됩니다
근데 병원 여러개를 돌리고 싶은데
여러 병원을 켜놓고 실행하면 최근 병원만 자동새로고침 되고
바로 직전 병원의 창은 자동 새로고침이 풀립니다 개발자님 ㅜㅜ

**Comment by changdocjjang** [comment]
재부팅 하니 자동으로 새로고침 되네요 제작자님
병원 숫자들 다 찾아서 창 켜놓으면 자동 예약 되는거죠?

**Comment by changdoc** [comment]
네 동작하는 설정 값이 여러 창을 켜도 다 공유가 되는 형태라 여러병원을 페이지를 열어놓은 상태에서 한곳에서 자동 예약 시작을 눌렀다면 나머지 창에서는 자동 예약 버튼을 누르는게 아니라 브라우저에서 새로고침을 하면 자동 예약 시도로 동작할거에요.

네 잔여 백신이 발생하게되면 페이지 이동을 하게 동작하는 방식이고요
정확하게는 예약 시도를 하는거라 다른 사람이 먼저 예약 시도가 되었다면 예약 실패할 가능성도 있긴합니다.

어제 문의주시던 두 분은 실패 페이지가 떴지만 병원에서 예약 되었다고 연락을 받으셨다고 하시더라고요.

**Comment by changdocjjang** [comment]
아 넵 감사합니다 잘 작동중입니다

혹시 개인정보 필수 동의란은 체크해도 새로고침시 자동 해제가 되는데
예약 시도시 자동 필수 체크 되나요?
궁금증은 다 해소되었는데 마지막으로 마음에 걸리는 부분이 있어 문의드립니다

자꾸 귀찮게 해드려서 죄송합니다

**Comment by changdoc** [comment]
![image](https://user-images.githubusercontent.com/1879494/124870246-5b838d00-dffd-11eb-9594-569fecdc8ba1.png)
이 화면에서 새로고침이 수행되어야하는데 개인 정보 필 수 동의란 체크는 안보이는데요. 혹시 다른곳을 확인중이신걸까요?

**Comment by The-pure-Groot** [comment]
> ![image](https://user-images.githubusercontent.com/1879494/124870246-5b838d00-dffd-11eb-9594-569fecdc8ba1.png)
> 이 화면에서 새로고침이 수행되어야하는데 개인 정보 필 수 동의란 체크는 안보이는데요. 혹시 다른곳을 확인중이신걸까요?

제가 새로운 이슈에 올렸어요 확인 부탁드립니다

**Comment by changdoc** [comment]
#9 에서 개인정보 필수 동의 체크 관련 이슈 확인 가능합니다.

**Comment by changdoc** [comment]
크롬 스토어에 1.0.1 버전으로 공개되어 본건 close합니다.
