### ISSUE TITLE
제작자님 인증서하고난 뒤에 개인정보 동의때문에 자동예약이 안되네요ㅠㅠ

### ISSUE THREAD

**Issue by The-pure-Groot** [changdoc/naver-vaccine-macro#9]
![234](https://user-images.githubusercontent.com/86877028/124887263-f6856280-e00f-11eb-9333-333b9e9b92bc.JPG)

이거는 자동으로 하려면 방법 없을까요?

자동예약하면 동의체크가 풀려요...

한번 동의했던사람은 

![3333](https://user-images.githubusercontent.com/86877028/124888383-0487b300-e011-11eb-8cfb-af5f08a0be76.JPG)

이렇게 뜹니다

**Comment by changdoc** [comment]
음 만들면서 제가 겪지 못한 증상이라 확인해보도록 하겠습니다.

**Comment by The-pure-Groot** [comment]
네 부탁드립니다!

**Comment by changdoc** [comment]
아하.. 예약 신청 내역 페이지 가서 개인 정보 수집 동의 철회 하니까 저도 나오군요. 자동으로 선택되도록 수정 진행해보겠습니다.

**Comment by changdoc** [comment]
https://github.com/changdoc/naver-vaccine-macro/commit/48c338c4a5b9935247cf37393c3544f7242fa9e8

왠지 처음 휴대폰 인증할때 개인정보 수집 동의 여부가 있었을거 같긴한데 인증을 다시 안해봐서 우선 저렇게 선택항목이 나오면 자동으로 체크하도록 수정 진행했습니다.

예약 시도까지 이어지는지는 검증이 필요하긴한데 예상한바로는 정상처리 될 것 같네요.

**Comment by The-pure-Groot** [comment]
빠른처리 감사합니다 혹시 수정본은 언제 올라오는지 알수 있을까요?

**Comment by changdoc** [comment]
아직 심사를 안넣은 상태라 내일은 우선 master branch로 받아서 시도 하시는게 좋을 것 같습니다.

크롬 스토어에 배포는 제가 테스트로 동작 이상 없는지 체크 하고 진행하고 있어서 좀 더 늦어 질 듯 합니다.

**Comment by changdoc** [comment]
오늘 테스트 결과 수정한 버전으로 예약 시도 가능한 부분 확인이 되었네요.
크롬 쪽 버전도 패치 등록 해두겠습니다. 배포 완료 되면 본건 close할게요.

**Comment by changdoc** [comment]
1.0.2버전이 크롬 웹스토어에 공개되어 본 이슈는 close합니다.
